// Functional checks for combat commands, using the real arena and HUD.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

module.exports = async ({js, waitFor, ready, win, dist}) => {
  const fire = '#player_hud_spells';
  const press = keyCode => {
    win.webContents.sendInputEvent({type: 'keyDown', keyCode});
    win.webContents.sendInputEvent({type: 'keyUp', keyCode});
  };
  // Esc opens the game menu; its Abandon entry opens the confirmation.
  const openAbandonDialog = async () => {
    press('Escape');
    await waitFor(`Boolean(document.querySelector('[role="dialog"] .game_menu_panel .exit_game_label'))`);
    await js('document.querySelector(".game_menu_panel .exit_game_label").click()');
    await waitFor(`Boolean(document.querySelector('[role="dialog"] .exit_game_menu'))`);
  };
  await js(`(() => {
    const {arena} = combatCheck;
    window.dockTurn = {...arena.turnee};
    window.dockCommands = [];
    ['spell', 'useitem', 'passTurn', 'abandonGame'].forEach(event => arena.socket.on(event, () => dockCommands.push(event)));
  })()`);
  await js(`(() => {
    const {arena} = combatCheck;
    window.originalSettings = {...arena.gameSettings};
    arena.gameSettings.game0 = true;
    arena.gameSettings.mode = 1; // PlayMode.TUTORIAL
    arena.refreshOverview();
  })()`);
  await ready();
  assert.equal(await js('Boolean(document.querySelector(".hud-container")?.getClientRects().length)'), false,
    'The initial tutorial overview stays hidden');
  press('Escape');
  await waitFor(`Boolean(document.querySelector('[role="dialog"] .game_menu_panel'))`);
  assert.equal(await js(`Boolean(document.querySelector('[role="dialog"] .exit_game_menu'))`), false, 'Escape offers the menu, not the abandon confirmation');
  assert.equal(await js('document.querySelectorAll(".game_menu_panel button").length >= 2'), true, 'The menu offers settings and abandon');
  assert.deepEqual(await js('dockCommands'), [], 'Opening the menu must not abandon');
  await ready();
  assert.equal(await js('document.activeElement.matches(".game_menu_panel [data-desktop-cancel]")'), true,
    'The combat menu focuses Resume');
  await js('document.querySelector(".game_menu_panel [data-desktop-cancel]").click()');
  await waitFor(`!document.querySelector('[role="dialog"]')`);
  assert.deepEqual(await js('dockCommands'), [], 'Resume closes the menu without sending a combat action');
  press('Escape');
  await waitFor(`Boolean(document.querySelector('[role="dialog"] .game_menu_panel'))`);
  press('Escape');
  await waitFor(`!document.querySelector('[role="dialog"]')`);
  await openAbandonDialog();
  assert.deepEqual(await js('dockCommands'), [], 'Opening the tutorial exit dialog must not abandon');
  await ready();
  assert.equal(await js('document.activeElement.matches(".exit_game_menu [data-desktop-cancel]")'), true);
  press('Escape');
  await waitFor(`!document.querySelector('[role="dialog"]')`);
  assert.deepEqual(await js('dockCommands'), [], 'Cancelling must preserve the tutorial');
  await js('Object.assign(combatCheck.arena.gameSettings, originalSettings); combatCheck.arena.refreshOverview()');
  await ready();
  await js(`document.querySelector('${fire}').focus()`);
  press('Space');
  await waitFor('dockCommands.length === 1');
  assert.deepEqual(await js('dockCommands'), ['passTurn'], 'Space passes even when a spell button has focus');
  assert.equal(await js('combatCheck.arena.selectedPlayer.pendingSpell'), null);
  await js("dockCommands = []; document.dispatchEvent(new KeyboardEvent('keydown', {code: 'Space', key: ' ', repeat: true, bubbles: true}))");
  await ready();
  assert.deepEqual(await js('dockCommands'), [], 'Holding Space must not pass repeatedly');
  await js("window.dockInput = document.createElement('input'); document.body.append(dockInput); dockInput.focus()");
  press('Space');
  await ready();
  assert.deepEqual(await js('dockCommands'), [], 'Typing a space must not pass');
  await js('dockInput.remove()');
  await openAbandonDialog();
  await ready();
  press('End');
  await ready();
  assert.deepEqual(await js('dockCommands'), [], 'An open dialog blocks passing an otherwise available turn');
  press('Escape');
  await waitFor(`!document.querySelector('[role="dialog"]')`);
  await js(`document.querySelector('${fire}').click()`);
  await waitFor('Boolean(document.querySelector(".combat-status-banner > span[data-tone=targeting]"))');
  assert.equal(await js('document.querySelector(".player_bar_mana meter").value'), 22);
  assert.equal(await js('document.querySelector(".player_bar_pass_turn").disabled'), true);
  press('Space');
  await ready();
  assert.deepEqual(await js('dockCommands'), [], 'Space respects targeting guards');
  await openAbandonDialog();
  await ready();
  assert.equal(await js('document.activeElement.matches(".exit_game_menu [data-desktop-cancel]")'), true);
  assert.equal(await js('combatCheck.arena.selectedPlayer.pendingSpell'), 0, 'Opening the dialog preserves targeting');
  press('End');
  await ready();
  assert.deepEqual(await js('dockCommands'), [], 'A dialog must block passing or abandoning without confirmation');
  press('Space');
  await waitFor(`!document.querySelector('[role="dialog"]')`);
  assert.equal(await js('combatCheck.arena.selectedPlayer.pendingSpell'), 0, 'Space activates Cancel without passing the turn');
  await openAbandonDialog();
  press('Escape');
  await waitFor(`!document.querySelector('[role="dialog"]')`);
  assert.deepEqual(await js('dockCommands'), []);
  await js('combatCheck.arena.selectedPlayer.cancelSkill()');
  await js('combatCheck.arena.processTurnee({...dockTurn, team: 2, num: 1, turnNumber: 9})');
  await waitFor('document.querySelector(".enemy_turn_banner")?.textContent === "Enemy Turn"');
  assert.equal(await js('document.querySelectorAll("button.player_bar_action, .player_bar_character").length'), 0);
  press('Space');
  await openAbandonDialog();
  press('Escape');
  await waitFor(`!document.querySelector('[role="dialog"]')`);
  assert.deepEqual(await js('dockCommands'), [], 'Enemy turn must not send actions');
  await js('combatCheck.arena.getPlayer(1, 3).setHP(55)');
  await js('combatCheck.arena.processTurnee({...dockTurn, turnNumber: 10})');
  await waitFor('document.querySelector(".player_bar_container").dataset.active === "true"');
  assert.equal(await js('document.querySelector(".player_bar_stat meter").value'), 55);
  win.show();
  win.focus();
  // Focusing the native window alone can leave the renderer unfocused on macOS.
  // In that state element.focus() changes activeElement without firing tooltip focus events.
  win.webContents.focus();
  await waitFor('document.hasFocus()');
  await ready();
  await js(`document.activeElement?.blur(); document.querySelector('${fire}').focus()`);
  await waitFor('document.querySelector("#combat-action-details .item-preview-name")?.textContent === "Fire"');
  assert.equal(await js('document.querySelectorAll("#combat-action-details .item-preview-classes").length'), 0);
  await ready();
  fs.writeFileSync(path.join(dist, 'dock-tooltip.png'), (await win.webContents.capturePage()).toPNG());
  await js('document.activeElement.blur()');
  await js('combatCheck.arena.selectedPlayer.mp = 0; combatCheck.arena.refreshBox()');
  await waitFor(`document.querySelector('${fire}').getAttribute('aria-label').includes('Not enough MP')`);
  await js(`document.querySelector('${fire}').click()`);
  await waitFor(`document.querySelector('.combat-action-feedback')?.textContent === 'Not enough mana: needs 10 MP, you have 0.'`);
  assert.equal(await js('combatCheck.arena.selectedPlayer.pendingSpell'), null);
  assert.deepEqual(await js('dockCommands'), [], 'A low-mana dock click explains the failure without sending an action');
  await js("combatCheck.arena.selectedPlayer.mp = 32; combatCheck.arena.selectedPlayer.statuses.Mute = 3; combatCheck.arena.refreshBox()");
  await waitFor(`document.querySelector('${fire}').getAttribute('aria-label').includes('Silenced')`);
  await js(`document.querySelector('${fire}').click()`);
  await waitFor(`document.querySelector('.combat-action-feedback')?.textContent === 'Silenced: choose another action.'`);
  assert.equal(await js('combatCheck.arena.selectedPlayer.pendingSpell'), null);
  assert.deepEqual(await js('dockCommands'), [], 'A silenced dock click explains the failure without sending an action');
  assert.equal(await js('document.querySelectorAll("button[data-tooltip-item-type=spells]").length'), 2);
  await js("combatCheck.arena.selectedPlayer.statuses.Mute = 0; combatCheck.arena.refreshBox()");
  await js('combatCheck.arena.selectOwnUnit(combatCheck.arena.getPlayer(1, 2))');
  await waitFor('document.querySelector(".player_bar_container").dataset.active === "false"');
  await js(`document.querySelector('${fire}').click()`);
  await js("combatCheck.arena.selectedPlayer.onKey(combatCheck.arena.selectedPlayer.getSpellsIndex())");
  assert.equal(await js('combatCheck.arena.selectedPlayer.pendingSpell'), null, 'An inspected ally cannot act out of turn');
  await js('combatCheck.arena.selectTurnee()');
  await waitFor('document.querySelector(".player_bar_container").dataset.active === "true"');
  await js(`document.querySelector('${fire}').focus()`);
  win.webContents.sendInputEvent({type: 'keyDown', keyCode: 'Return'});
  win.webContents.sendInputEvent({type: 'keyUp', keyCode: 'Return'});
  await waitFor('combatCheck.arena.selectedPlayer.pendingSpell === 0');
  await js('combatCheck.arena.selectedPlayer.cancelSkill(); document.activeElement.blur()');
  await js('combatCheck.arena.selectedPlayer.setSpells([0, 3, 6, 1, 2]); combatCheck.arena.selectedPlayer.setInventory([0, 1, 8, 10, 11]); combatCheck.arena.refreshBox()');
  // Captures are reviewed manually, not used as appearance assertions.
  for (const [width, height, scale] of [[1600, 900, 100], [1280, 720, 100], [1280, 720, 130], [960, 540, 100]]) {
    win.setContentSize(width, height);
    await js(`document.documentElement.style.fontSize = '${scale}%'`);
    await ready();
    fs.writeFileSync(path.join(dist, `dock-${width}-${scale}.png`), (await win.webContents.capturePage()).toPNG());
  }
  await js('document.documentElement.style.fontSize = "100%"; combatCheck.resync()');
  await waitFor('document.querySelectorAll("button.player_bar_action").length === 4');
  assert.equal(await js('document.querySelector(".player_bar_stat meter").value'), 80, 'Reconnect must refresh the selected character');
  await js('window.exitCommands = []; combatCheck.arena.socket.on("abandonGame", () => exitCommands.push("abandonGame")); combatCheck.arena.gameSettings.game0 = true; combatCheck.arena.gameSettings.mode = 1; combatCheck.arena.refreshOverview(); window.exitingGame = combatCheck.arena.game; void 0');
  await ready();
  await openAbandonDialog();
  await js('document.querySelector(".exit_game_menu .game_leave_btn").click()');
  await waitFor('location.pathname === "/play" && !document.querySelector("#scene canvas") && !exitingGame.loop.running');
  assert.deepEqual(await js('exitCommands'), ['abandonGame'], 'Confirming must abandon exactly once and stop the tutorial');
  console.log('Tutorial Escape: hidden overview, safe cancel, confirmed exit and engine cleanup pass');
  console.log('Command dock: targeting, mana preview, enemy-turn guards, live stats, silence, inspection, keyboard and reconnect pass');
};
