FROM oven/bun:1.3.14 as builder

WORKDIR /usr/src/app

# Copy root package.json and lockfile
COPY package.json bun.lock ./
# Copy all package.json to their correct directory paths
COPY api/functions/package.json ./api/functions/
COPY client/package.json ./client/
COPY matchmaker/package.json ./matchmaker/
COPY server/package.json ./server/
COPY shared/package.json ./shared/

# Install dependencies
RUN bun ci --filter "./server"

COPY shared/ ./shared/

COPY server/tsconfig.docker.json ./tsconfig.json

COPY server/src/ ./src/

RUN bun run build

FROM oven/bun:1.3.14-slim

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/node_modules ./node_modules

COPY --from=builder /usr/src/app/dist ./dist

COPY server/.production.env ./.env

EXPOSE 3123

CMD ["bun", "run", "start"]
