FROM oven/bun:1.3.8

WORKDIR /usr/src/app

# Copy root package.json and lockfile
COPY package.json bun.lock ./
# Copy all package.json to their correct directory paths
COPY api/functions/package.json ./api/functions/
COPY client/package.json ./client/
COPY matchmaker/package.json ./matchmaker/
COPY server/package.json ./server/
COPY shared/package.json ./shared/

# Install dependencies
RUN bun ci --filter "./matchmaker"

# Copy source files
COPY shared/ ./shared/
COPY matchmaker/tsconfig.docker.json ./matchmaker/tsconfig.json
COPY matchmaker/src/ ./matchmaker/src/

WORKDIR /usr/src/app/matchmaker

RUN bun run build

FROM oven/bun:1.3.8-slim

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/matchmaker/node_modules ./node_modules
COPY --from=builder /usr/src/app/matchmaker/dist ./dist
COPY matchmaker/.production.env ./.env

EXPOSE 3000

CMD ["bun", "run", "start"]
