FROM oven/bun:1.4.0 AS builder

WORKDIR /usr/src/app

COPY matchmaker/package.json ./
COPY matchmaker/bun.lock ./

RUN bun ci

COPY shared/ ./shared

COPY matchmaker/tsconfig.docker.json ./tsconfig.json
COPY matchmaker/src/ ./src/

RUN bun run build

FROM oven/bun:1.4.0-slim

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/node_modules ./node_modules

COPY --from=builder /usr/src/app/dist ./dist

EXPOSE 3000

CMD ["bun", "dist/src/matchmaker.js"]
